---
# https://kubernetes.io/docs/reference/config-api/kubeadm-config.v1beta3/#kubeadm-k8s-io-v1beta3-ClusterConfiguration
apiVersion: kubeadm.k8s.io/v1beta4
kind: ClusterConfiguration
kubernetesVersion: v1.30.3
controlPlaneEndpoint: node-rk1
clusterName: test
networking:
  podSubnet: 10.244.0.0/24
---
apiVersion: kubeadm.k8s.io/v1beta4
kind: InitConfiguration
nodeRegistration:
  criSocket: unix:///var/run/containerd/containerd.sock
# localAPIEndpoint:
#   advertiseAddress: 192.168.2.247
#   bindPort: 6443
skipPhases:
  - addon/kube-proxy
---
# https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet/
apiVersion: kubelet.config.k8s.io/v1
kind: KubeletConfiguration
cgroupDriver: systemd
maxPods: 250
