---
# Install Ansible collections
collections:
  - name: community.general
    version: 10.2.0
    source: https://galaxy.ansible.com
  - name: ansible.posix
    version: 2.0.0
    source: https://galaxy.ansible.com
  - name: kubernetes.core
    version: 5.0.0
    source: https://galaxy.ansible.com
