apiVersion: v1alpha1
kind: KubeClusterConfig
clusterName: test
endpoint: https://192.168.1.55:6443
---
apiVersion: v1alpha1
kind: KubeNodeConfig
taints:
  $patch: delete
---
apiVersion: v1alpha1
kind: KubeFlannelCNIConfig
# Disables the default CNI
$patch: delete
