ingress-nginx:
  controller:
    config:
      custom-http-errors: 401,403,404,500,501,502,503
      use-forwarded-headers: "true"
    ingressClassResource:
      default: true

    kind: Deployment
    replicaCount: 2
    minAvailable: 0
    maxUnavailable: 2

    service:
      annotations:
        metallb.universe.tf/address-pool: public-ip-pool
      # externalIPs:
      #   - 38.242.242.71
      nodePorts:
        http: 32080
        https: 32443

    resources:
      limits:
        memory: 512Mi
      requests:
        cpu: 50m
        memory: 256Mi

    metrics:
      enabled: true
      serviceMonitor:
        enabled: true

  revisionHistoryLimit: 2

  defaultBackend:
    enabled: true
    image:
      repository: ghcr.io/tarampampam/error-pages
      tag: 3.3.2
    extraEnvs:
    - name: TEMPLATE_NAME
      value: ghost
    - name: SHOW_DETAILS
      value: 'true'
    resources:
      limits:
        memory: 16Mi
      requests:
        cpu: 10m
        memory: 8Mi
