apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: no-sync
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Autosync is disabled
  sourceRepos:
    - '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  destinations:
    - namespace: '*'
      server: '*'
  syncWindows:
    - kind: deny
      # We do not want autosync, but there is no way to describe this.
      schedule: '0 0 * * *'
      duration: 24h
      manualSync: true
      applications:
        - '*'
      namespaces:
        - '*'
      clusters:
        - '*'
