apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgBRgnqyUfog+jGX/etarP8+QjDTJPsb4GYwaM6KgUR4nW4m0Ipfnh8lmFESWAu/fj90Iru39E1lW814Lxsp50UqFB7Jro/Xz7VZZWtm+af4ERx4AGlpA7SPazSbGDH81HvG3bvoCimi1TzYEb00iszEYPkwtUyLmQu0P6HgNym1nKdkIMgT9gl3S7DEsKLbTvcp+rWMCEG06KBATKfYPrQ8RoenpWltQMuef/pwNz4lbESCBqPcN9tY75XglfNtftCeWp249+V91EuKPrF6SrFt1cggr9lzowtUXRG3BZDzUl49i/BmyogZFSB87JfIEFz1YEpfLDBDF+91RksuIDTFVCoG2nrbFaUTt6KAEal6ZIsfsjd5fSjbevfKjaLfXmCyBZ6vT1SY4llX4Ar4iFcOGRooNnxmwi/0FZTxXXmeZqrp+fCHM1P8mrkTN+5B/bgNYG6GjXo1hTnJY0AnsgAfslR1dvhA9am3BdCEJRsfoZ3WxP4KWOVQ4yEkiKiI/63SyHDZktCQeqk8lfIcxuT1rsEBMZI8LPxdClqBj/BkLPc2rsloo9Zx5O/RkKu9PIohDPqGZpcuqsJSdr7a2rd18W2XULUFPaoAVq87uuXoBx8OCsbBoHO51cLaWqu9zHDrwsw+xpKnrVinLm0RsItiABxpiP0lJJqCy7a79CqT9aqmK8R3bbMqJoankAk1Idx7ekvNyc1CUh5rsYhNCIPxi9DVNN+hx1ysCeXA4vnLgBrWmkOtbgpC
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: cert-manager
    type: Opaque
