apiVersion: v2
name: node-feature-discovery
version: 1.0.8

dependencies:
  - name: node-feature-discovery
    version: 0.16.4
    repository: https://kubernetes-sigs.github.io/node-feature-discovery/charts
