apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: external-dns
spec:
  encryptedData:
    cloudflare_api_token: AgAJXngOC4D3MfgGGhop+Wa2V+T9Sk/gScbufvtbmdCUpWEQ0wWcKa7LDaEa1a5RS67jqExuoHYraeaejkp7uEp4RH8vl2LVlGEVMPpHQRFndmOdGV4oKKoFIBI+c4qZ9HwX+3Yqu4EcwQK/YwXqe8QrSXOidCvVCtZQJdO4Vz8y82zpSimW3dPR1xSqxpWLIyeW2csoUvjOowe1HwhXyY9KlI3cxx1jpbWTg9xcAd0q4bXZSS0mGQF91NScxZNt4iaioQNOMVQ7iMKg0DzWRP2O65mkQGEoWP6uTWP1duYk7gA4SCBqnumX1GQAXJvY3Juekc108xStsmw7JHxQL+iEwZwkPJ2KhQKqWANbzZKxjVt9BaYPcFhxE9o6QOne58XtIittuxfR3JTE20UnDNYITeasUDHlPbyF0INM6a0Zcms9jygMTSE1oRiCNEFly1k+ZLMDEom3nOEB+cgiGEbHI5VFENP1gOKqlb4HCgBwFi27KI8YSqigUguJLbjOEWHoeA+Lfkb8zOtE0xJsAx+U2pHhyzTE+UKRBZUqRyBi1zQ71uZgs0O+iwViP8yq0FL32ZTomuiO8vTIFZJMqkKXa5IVUAAtvNM7PFfAReT5O45WDJw5ygd0pMZqIV1z7ET5FmvyjEI7Cc9sy24TZc+dz4qNxjMBgXmnD1i1nHHZROTWdA05ocIOqOS+5yw9S57Whz2FJwvahMgqOHjoTfW/73nBzIQRv4DAg9GRp2dDZH5kWYskoZMP
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: external-dns
    type: Opaque
