# .github/workflows/ansible-lint.yml
name: ansible-lint
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Ansible Lint
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Setup Python
        uses: actions/setup-python@f677139bbe7f9c59b41e40162b753c062f5d49a3 # v5.2.0
        with:
          python-version: 3.12
          cache: pip
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          ansible-galaxy install -r requirements.yaml
      - name: Run ansible-playbook syntax-check
        run: cd ./ansible && ansible-playbook playbook.yaml --syntax-check
      - name: Run ansible-lint
        run: ansible-lint ./ansible/playbook.yaml --profile moderate
