machine:
  type: worker

  # network:
  #   hostname: jotunheim_3

  disks:
    - device: /dev/nvme0n1
      partitions:
        - mountpoint: /var/mnt/nvme1
---
apiVersion: v1alpha1
kind: UnattendedInstallConfig
provisioning:
  diskSelector:
    match: disk.dev_path == "/dev/mmcblk0"
