machine:
  type: controlplane
---
apiVersion: v1alpha1
kind: DHCPv4Config
name: end0
---
apiVersion: v1alpha1
kind: UnattendedInstallConfig
provisioning:
  diskSelector:
    match: disk.dev_path == "/dev/mmcblk0"
  wipe: false
